/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package inventorymanagementsystem;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jahangiralamdiu
 */
public class IndividualStockReport extends javax.swing.JFrame {

    /**
     * Creates new form IndividualStockReport
     */
    public IndividualStockReport() {
        initComponents();
        initProductID();
    }
    
      public void initProductID(){
          
          
       
        PreparedStatement pstm=null;
        try {
            connection=new ConnectivitySupport();
            pstm=connection.getConn().prepareStatement("select product_id, product_name from product");           
            ResultSet rs=pstm.executeQuery();
             comboProductID.addItem("Select Product ID");
            while(rs.next()){
              comboProductID.addItem(rs.getInt(1) + "-"+ rs.getString(2));
            }
                    
        } catch (SQLException ex) {
            Logger.getLogger(OrderForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(IndividualStockReport.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboProductID = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        singleStock = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Select Product ID :");

        comboProductID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboProductIDActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(singleStock);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(192, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(comboProductID, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboProductID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboProductIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboProductIDActionPerformed
        // TODO add your handling code here:
           try {
            connection=new ConnectivitySupport();
            String query="select s.stock_id Stock_ID, s.product_id Product_ID, p.product_name Name, s.avail_stock Available, s.unit_price Cost_Price,"
                    + "s.sales_price Sale_Price, s.reorder_level Last_Added, s.reorder_date Add_date from stock s, product p where"
                    + " p.product_id=s.product_id and p.product_id=?";
            
            PreparedStatement pstm=connection.getConn().prepareCall(query);
            
            pstm.setString(1, comboProductID.getSelectedItem().toString().split("-")[0]);
            
            ResultSet rs=pstm.executeQuery();
            rm.setResultSet(rs);
            singleStock.setModel(rm);
         
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ClientEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ClientEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_comboProductIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IndividualStockReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IndividualStockReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IndividualStockReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IndividualStockReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IndividualStockReport().setVisible(true);
            }
        });
    }
    private ResultsModel rm=new ResultsModel();
    private ConnectivitySupport connection;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboProductID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable singleStock;
    // End of variables declaration//GEN-END:variables
}
