/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorymanagementsystem;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.tree.DefaultTreeCellRenderer;
import javax.swing.tree.TreePath;

/**
 *
 * @author jahangiralamdiu
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        ctell();
        this.setIconImage(new ImageIcon(getClass().getResource("logoinventory.jpg")).getImage());
        mainTab.addTab("", new Greetings());

    }

    void imageSize() {
        ImageIcon buynow = new ImageIcon("images/buynow.png");

    }

    void ctell() {
        ImageIcon leafIcon = new ImageIcon("images/logo.jpg");
        if (leafIcon != null) {
            DefaultTreeCellRenderer renderer
                    = new DefaultTreeCellRenderer();
            renderer.setLeafIcon(leafIcon);
            mainTree.setCellRenderer(renderer);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btGroup = new javax.swing.ButtonGroup();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainTree = new javax.swing.JTree();
        mainTab = new javax.swing.JTabbedPane();
        mainToolbar = new javax.swing.JToolBar();
        buy = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItem29 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenuItem35 = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenuItem37 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem38 = new javax.swing.JMenuItem();
        jMenuItem39 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem40 = new javax.swing.JMenuItem();

        jMenuItem16.setText("jMenuItem16");

        jMenuItem20.setText("jMenuItem20");

        jMenuItem10.setText("jMenuItem10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 760));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Inventory");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Order Form");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Payment Form");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Products");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Product Entry");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Product Group Entry");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Clients");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Client Entry");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Client Type");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Reports");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Sales");
        javax.swing.tree.DefaultMutableTreeNode treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Specific Sales");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Daily Sales");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Weakly Sales");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Monthly Sales");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Yearly Sales");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("All Sales");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Purchase");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Specific Purchase");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Daily Purchase");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Weakly Purchase");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Monthly Purchase");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Yearly Purchase");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("All Purchase");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Stock");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Specific Stock");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("All Stock");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        mainTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        mainTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                mainTreeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(mainTree);

        jSplitPane1.setLeftComponent(jScrollPane1);

        mainTab.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jSplitPane1.setRightComponent(mainTab);

        mainToolbar.setBackground(new java.awt.Color(255, 255, 255));
        mainToolbar.setRollover(true);

        buy.setIcon(new javax.swing.ImageIcon("D:\\Java\\Projects\\Swing\\InventoryByJahangir\\images\\sale (1).png")); // NOI18N
        buy.setToolTipText("Sales Order");
        buy.setFocusable(false);
        buy.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buy.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyActionPerformed(evt);
            }
        });
        mainToolbar.add(buy);

        jButton1.setIcon(new javax.swing.ImageIcon("D:\\Java\\Projects\\Swing\\InventoryByJahangir\\images\\buynow.png")); // NOI18N
        jButton1.setToolTipText("Purchase Order");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        mainToolbar.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon("D:\\Java\\Projects\\Swing\\InventoryByJahangir\\images\\coin_stacks_copper_share.png")); // NOI18N
        jButton2.setToolTipText("Payment");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        mainToolbar.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon("D:\\Java\\Projects\\Swing\\InventoryByJahangir\\images\\kuser.png")); // NOI18N
        jButton3.setToolTipText("Client Entry");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        mainToolbar.add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon("D:\\Java\\Projects\\Swing\\InventoryByJahangir\\images\\newp.jpg")); // NOI18N
        jButton4.setToolTipText("Product Entry");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        mainToolbar.add(jButton4);

        jButton5.setIcon(new javax.swing.ImageIcon("D:\\Java\\Projects\\Swing\\InventoryByJahangir\\images\\reports (1).png")); // NOI18N
        jButton5.setToolTipText("View Reports");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        mainToolbar.add(jButton5);

        jButton6.setIcon(new javax.swing.ImageIcon("D:\\Java\\Projects\\Swing\\InventoryByJahangir\\images\\web_find.png")); // NOI18N
        jButton6.setToolTipText("Search ");
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        mainToolbar.add(jButton6);

        jButton7.setIcon(new javax.swing.ImageIcon("D:\\Java\\Projects\\Swing\\InventoryByJahangir\\images\\symbol_help.png")); // NOI18N
        jButton7.setToolTipText("Help");
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mainToolbar.add(jButton7);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenu1.setMnemonic(KeyEvent.VK_F);
        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon("D:\\Java\\Projects\\Swing\\InventoryByJahangir\\images\\tab_new_raised.png")); // NOI18N
        jMenuItem1.setText("New Sales");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon("D:\\Java\\Projects\\Swing\\InventoryByJahangir\\images\\gnome_document_new (1).png")); // NOI18N
        jMenuItem2.setText("New Purchase");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon("D:\\Java\\Projects\\Swing\\InventoryByJahangir\\images\\coin_stacks_copper_share.png")); // NOI18N
        jMenuItem3.setText("Payment");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);
        jMenu1.add(jSeparator1);
        jMenu1.add(jSeparator2);

        jMenu4.setIcon(new javax.swing.ImageIcon("D:\\Java\\Projects\\Swing\\InventoryByJahangir\\images\\kuser.png")); // NOI18N
        jMenu4.setText("Client");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon("D:\\Java\\Projects\\Swing\\InventoryByJahangir\\images\\window_new (1).png")); // NOI18N
        jMenuItem4.setText("New Client");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuItem5.setText("New Client Type");
        jMenu4.add(jMenuItem5);

        jMenu1.add(jMenu4);
        jMenu1.add(jSeparator3);

        jMenu5.setText("Product");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setIcon(new javax.swing.ImageIcon("D:\\Java\\Projects\\Swing\\InventoryByJahangir\\images\\newp.jpg")); // NOI18N
        jMenuItem6.setText("New Product");
        jMenu5.add(jMenuItem6);

        jMenuItem7.setText("New Product Group");
        jMenu5.add(jMenuItem7);

        jMenu1.add(jMenu5);
        jMenu1.add(jSeparator4);

        jMenu6.setIcon(new javax.swing.ImageIcon("D:\\Java\\Projects\\Swing\\InventoryByJahangir\\images\\reports (1).png")); // NOI18N
        jMenu6.setText("Reports");

        jMenu7.setText("Sales");

        jMenuItem11.setText("Specific Sale");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem11);

        jMenuItem8.setText("Daily Sales");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem8);

        jMenuItem12.setText("Weakly Sales");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem12);

        jMenuItem13.setText("Monthly Sales");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem13);

        jMenuItem14.setText("Yearly Sales");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem14);

        jMenuItem15.setText("All Sales");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem15);

        jMenu6.add(jMenu7);

        jMenu8.setText("Purchases");

        jMenuItem17.setText("Specific");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem17);

        jMenuItem18.setText("Daily Purchases");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem18);

        jMenuItem19.setText("Weakly Purchases");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem19);

        jMenuItem21.setText("Monthly Purchases");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem21);

        jMenuItem22.setText("Yearly Purchases");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem22);

        jMenuItem23.setText("All Purchases");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem23);

        jMenu6.add(jMenu8);

        jMenu9.setText("Stock");

        jMenuItem9.setText("Specific Stock");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem9);

        jMenuItem24.setText("All Stocks");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem24);

        jMenu6.add(jMenu9);

        jMenu10.setText("Payments");

        jMenuItem25.setText("Specific Payment");
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem25);

        jMenuItem26.setText("All Payments");
        jMenu10.add(jMenuItem26);

        jMenu6.add(jMenu10);

        jMenu1.add(jMenu6);
        jMenu1.add(jSeparator5);

        jMenuItem27.setText("Save");
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem27);

        jMenuItem28.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem28.setIcon(new javax.swing.ImageIcon("D:\\Java\\Projects\\Swing\\InventoryByJahangir\\images\\save (2).png")); // NOI18N
        jMenuItem28.setText("Save As");
        jMenu1.add(jMenuItem28);
        jMenu1.add(jSeparator6);

        jMenuItem29.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem29.setIcon(new javax.swing.ImageIcon("D:\\Java\\Projects\\Swing\\InventoryByJahangir\\images\\printer (1).png")); // NOI18N
        jMenuItem29.setText("Print");
        jMenu1.add(jMenuItem29);
        jMenu1.add(jSeparator7);

        jMenuItem30.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem30.setIcon(new javax.swing.ImageIcon("D:\\Java\\Projects\\Swing\\InventoryByJahangir\\images\\erase.png")); // NOI18N
        jMenuItem30.setText("Exit");
        jMenuItem30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem30ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem30);

        jMenuBar1.add(jMenu1);

        jMenu2.setMnemonic(KeyEvent.VK_E);
        jMenu2.setText("Edit");

        jMenuItem31.setText("Undo");
        jMenu2.add(jMenuItem31);

        jMenuItem32.setText("Redo");
        jMenu2.add(jMenuItem32);
        jMenu2.add(jSeparator8);

        jMenuItem33.setText("Cut");
        jMenu2.add(jMenuItem33);

        jMenuItem34.setText("Copy");
        jMenu2.add(jMenuItem34);

        jMenuItem35.setText("Paste");
        jMenu2.add(jMenuItem35);
        jMenu2.add(jSeparator9);

        jMenuItem36.setText("Find");
        jMenuItem36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem36ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem36);

        jMenuItem37.setText("Replace");
        jMenu2.add(jMenuItem37);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("View");

        btGroup.add(jCheckBoxMenuItem1);
        jCheckBoxMenuItem1.setText("Hide Toolbar");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jCheckBoxMenuItem1);

        btGroup.add(jCheckBoxMenuItem2);
        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("Show Toolbar");
        jCheckBoxMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jCheckBoxMenuItem2);

        jMenuBar1.add(jMenu3);

        jMenu11.setText("Help");

        jMenuItem38.setText("Find Help");
        jMenu11.add(jMenuItem38);

        jMenuItem39.setText("Contact");
        jMenu11.add(jMenuItem39);

        jMenuBar1.add(jMenu11);

        jMenu12.setText("About");

        jMenuItem40.setText("About Me");
        jMenu12.add(jMenuItem40);

        jMenuBar1.add(jMenu12);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 936, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_mainTreeValueChanged
        // TODO add your handling code here:
        String nodePath = evt.getPath().toString();
        TreePath[] paths = evt.getPaths();
        for (int i = 0; i < paths.length; i++) {
            {
                if (evt.isAddedPath(i)) {
                    String node = paths[i].getLastPathComponent().toString();
                    if (node.equals("Order Form")) {
                        mainTab.removeAll();
                        mainTab.addTab("", new OrderForm());

                    }
                    if (node.equals("Payment Form")) {
                        mainTab.removeAll();
                        mainTab.addTab("", new PaymentForm());
                    }

                    if (node.equals("Product Entry")) {
                        mainTab.removeAll();
                        mainTab.addTab("", new ProductEntryForm());

                    }
                    if (node.equals("Product Group Entry")) {
                        ProductGroup pg = new ProductGroup(new InventoryManagement(), true);
                        pg.setVisible(true);

                    }

                    if (node.equals("Client Entry")) {
                        mainTab.removeAll();
                        mainTab.addTab("", new ClientEntryForm());
                    }
                    if (node.equals("Reports")) {
                        mainTab.removeAll();
                        mainTab.addTab("", new ReportForm());
                    }
                    if (node.equals("Specific Sales")) {
                        IndividualSales indSales = new IndividualSales();
                        indSales.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                        indSales.setVisible(true);
                    }
                    if (node.equals("Daily Sales")) {
                        DaillySales ds = new DaillySales();
                        ds.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                        ds.setVisible(true);
                    }
                    if (node.equals("Weakly Sales")) {
                        WeaklySales wsales = new WeaklySales();
                        wsales.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                        wsales.setVisible(true);
                    }
                    if (node.equals("Monthly Sales")) {
                        MonthlySalesReport msales = new MonthlySalesReport();
                        msales.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                        msales.setVisible(true);
                    }
                    if (node.equals("Yearly Sales")) {
                        YearlySales ysales = new YearlySales();
                        ysales.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                        ysales.setVisible(true);
                    }
                    if (node.equals("All Sales")) {
                        AllSales allSales = new AllSales();
                        allSales.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                        allSales.setVisible(true);
                    }
                    if (node.equals("Specific Purchase")) {
                        IndividualPurchaseReport indPurchase = new IndividualPurchaseReport();
                        indPurchase.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                        indPurchase.setVisible(true);
                    }
                    if (node.equals("Daily Purchase")) {
                        DailyPurchase dsp = new DailyPurchase();
                        dsp.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                        dsp.setVisible(true);
                    }
                    if (node.equals("Weakly Purchase")) {
                        WeaklyPurchase wpurchase = new WeaklyPurchase();
                        wpurchase.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                        wpurchase.setVisible(true);
                    }
                    if (node.equals("Monthly Purchase")) {
                        MonthlyPurchaseReport mpurchase = new MonthlyPurchaseReport();
                        mpurchase.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                        mpurchase.setVisible(true);
                    }
                    if (node.equals("Yearly Purchase")) {
                        YearlyPurchase ypurchase = new YearlyPurchase();
                        ypurchase.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                        ypurchase.setVisible(true);
                    }
                    if (node.equals("All Purchase")) {
                        AllPurchases allPurchas = new AllPurchases();
                        allPurchas.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                        allPurchas.setVisible(true);
                    }

                    if (node.equals("Specific Stock")) {
                        IndividualStockReport strp = new IndividualStockReport();
                        strp.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                        strp.setVisible(true);
                    }
                    if (node.equals("All Stock")) {

                        AllStock allStock = new AllStock();
                        allStock.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                        allStock.setVisible(true);

                    }

                    break;
                } else {
                    break;
                }
            }
        }
    }//GEN-LAST:event_mainTreeValueChanged

    private void buyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyActionPerformed
        // TODO add your handling code here:
        mainTab.removeAll();
        mainTab.addTab("", new OrderForm());
    }//GEN-LAST:event_buyActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        // TODO add your handling code here:
        mainToolbar.setVisible(false);
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void jCheckBoxMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem2ActionPerformed
        // TODO add your handling code here:
        mainToolbar.setVisible(true);
    }//GEN-LAST:event_jCheckBoxMenuItem2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        mainTab.removeAll();
        mainTab.addTab("", new OrderForm());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        mainTab.removeAll();
        mainTab.addTab("", new PaymentForm());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        mainTab.removeAll();
        mainTab.addTab("", new ClientEntryForm());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        mainTab.removeAll();
        mainTab.addTab("", new ProductEntryForm());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        mainTab.removeAll();
        mainTab.addTab("", new ReportForm());
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                SearchForm dialog = new SearchForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {

                    }
                });
                dialog.setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        YearlySales ysales = new YearlySales();
        ysales.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        ysales.setVisible(true);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem25ActionPerformed

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem27ActionPerformed

    private void jMenuItem36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem36ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        mainTab.removeAll();
        mainTab.addTab("", new OrderForm());
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        mainTab.removeAll();
        mainTab.addTab("", new PaymentForm());
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem30ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem30ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        mainTab.removeAll();
        mainTab.addTab("", new OrderForm());
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        mainTab.removeAll();
        mainTab.addTab("", new ClientEntryForm());
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        IndividualSales indSales = new IndividualSales();
        indSales.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        indSales.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        DaillySales ds = new DaillySales();
        ds.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        ds.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        WeaklySales wsales = new WeaklySales();
        wsales.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        wsales.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        MonthlySalesReport msales = new MonthlySalesReport();
        msales.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        msales.setVisible(true);        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        AllSales allSales = new AllSales();
        allSales.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        allSales.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        IndividualPurchaseReport indPurchase = new IndividualPurchaseReport();
        indPurchase.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        indPurchase.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        DailyPurchase dsp = new DailyPurchase();
        dsp.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        dsp.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        WeaklyPurchase wpurchase = new WeaklyPurchase();
        wpurchase.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        wpurchase.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        MonthlyPurchaseReport mpurchase = new MonthlyPurchaseReport();
        mpurchase.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        mpurchase.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        YearlyPurchase ypurchase = new YearlyPurchase();
        ypurchase.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        ypurchase.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        AllPurchases allPurchas = new AllPurchases();
        allPurchas.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        allPurchas.setVisible(true);
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        IndividualStockReport strp = new IndividualStockReport();
        strp.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        strp.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        AllStock allStock = new AllStock();
        allStock.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        allStock.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    OrderForm of = new OrderForm();
    PaymentForm pf = new PaymentForm();
    ClientEntryForm cf = new ClientEntryForm();
    ProductEntryForm pfe = new ProductEntryForm();

    ReportForm rf = new ReportForm();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btGroup;
    private javax.swing.JButton buy;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem37;
    private javax.swing.JMenuItem jMenuItem38;
    private javax.swing.JMenuItem jMenuItem39;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem40;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane mainTab;
    private javax.swing.JToolBar mainToolbar;
    private javax.swing.JTree mainTree;
    // End of variables declaration//GEN-END:variables
}
