/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorymanagementsystem;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Jahangir
 */
public class ProductEntryForm extends javax.swing.JPanel {

    /**
     * Creates new form ClientEntryForm
     */
    public ProductEntryForm() {
        initComponents();
        productGroupInitiate();
        productIDInitiate();
        stockIDInitiate();
        txtDate.setDate(new java.util.Date());
    }

    void productIDInitiate() {
        try {
            connection = new ConnectivitySupport();
            Statement stm = connection.getConn().createStatement();

            ResultSet rs = stm.executeQuery("select MAX(product_id) from product");

            if (rs.next()) {
                txtProductID.setText(Integer.toString(rs.getInt("Max(product_id)") + 1));
            }
            rs.close();
            stm.close();
            connection = null;
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ClientEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ClientEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void productGroupInitiate() {
        try {
            connection = new ConnectivitySupport();
            Statement stm = connection.getConn().createStatement();

            ResultSet rs = stm.executeQuery("select *from product_group");

            comboProductGroup.addItem("Select Product Group");
            comboProductGroup.addItem("Create a new Group");
            while (rs.next()) {
                comboProductGroup.addItem(rs.getString(1) + "-" + rs.getString(2));
            }
            rs.close();
            stm.close();
            connection = null;
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ClientEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ClientEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    void stockIDInitiate() {
        try {
            connection = new ConnectivitySupport();
            Statement stm = connection.getConn().createStatement();

            ResultSet rs = stm.executeQuery("select MAX(stock_id) from stock");

            if (rs.next()) {
                txtStockID.setText(Integer.toString(rs.getInt(1) + 1));
            }
            rs.close();
            stm.close();
            connection = null;
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ClientEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ClientEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtProductID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comboProductGroup = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        txtProductName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCompanyName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtStockID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtUnitPrice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSalesPrice = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDate = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        productsTable = new javax.swing.JTable();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Vijaya", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Product Entry Form");

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Product Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        jPanel1.setLayout(new java.awt.GridLayout(0, 4, 20, 20));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Product ID :");
        jPanel1.add(jLabel2);
        jPanel1.add(txtProductID);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Product Group :");
        jPanel1.add(jLabel4);

        comboProductGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboProductGroupActionPerformed(evt);
            }
        });
        jPanel1.add(comboProductGroup);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Product Name");
        jPanel1.add(jLabel3);
        jPanel1.add(txtProductName);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Company Name :");
        jPanel1.add(jLabel9);
        jPanel1.add(txtCompanyName);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Stock ID:");
        jPanel1.add(jLabel6);
        jPanel1.add(txtStockID);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Unit Price");
        jPanel1.add(jLabel5);

        txtUnitPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnitPriceActionPerformed(evt);
            }
        });
        jPanel1.add(txtUnitPrice);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Sales Price");
        jPanel1.add(jLabel7);
        jPanel1.add(txtSalesPrice);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Quantity :");
        jPanel1.add(jLabel8);
        jPanel1.add(txtQuantity);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("Date :");
        jPanel1.add(jLabel10);
        jPanel1.add(txtDate);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0, 20, 20));

        jButton1.setIcon(new javax.swing.ImageIcon("D:\\Java\\Projects\\Swing\\InventoryByJahangir\\images\\save (1).png")); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon("D:\\Java\\Projects\\Swing\\InventoryByJahangir\\images\\tab_new_raised.png")); // NOI18N
        jButton2.setText("New");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon("D:\\Java\\Projects\\Swing\\InventoryByJahangir\\images\\gwenview.png")); // NOI18N
        jButton3.setText("Display");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon("D:\\Java\\Projects\\Swing\\InventoryByJahangir\\images\\search.png")); // NOI18N
        jButton4.setText("Search");
        jPanel2.add(jButton4);

        jButton5.setIcon(new javax.swing.ImageIcon("D:\\Java\\Projects\\Swing\\InventoryByJahangir\\images\\gnome_edit_delete (2).png")); // NOI18N
        jButton5.setText("Delete");
        jPanel2.add(jButton5);

        jButton6.setIcon(new javax.swing.ImageIcon("D:\\Java\\Projects\\Swing\\InventoryByJahangir\\images\\update.png")); // NOI18N
        jButton6.setText("Update");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);

        jButton7.setIcon(new javax.swing.ImageIcon("D:\\Java\\Projects\\Swing\\InventoryByJahangir\\images\\finaldelete.png")); // NOI18N
        jButton7.setText("Exit");
        jPanel2.add(jButton7);

        jScrollPane1.setViewportView(productsTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(45, 45, 45))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtUnitPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnitPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnitPriceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "Would Like to Save") == 0) {
            String query1 = "insert into product (product_id, product_name, company_name, group_id) values(?, ?, ?, ? )";
            try {
                connection = new ConnectivitySupport();
                PreparedStatement pstm1;
                PreparedStatement pstm2;
                PreparedStatement pstm3;
                pstm1 = connection.getConn().prepareCall(query1);
                pstm1.setInt(1, Integer.parseInt(txtProductID.getText()));
                pstm1.setString(2, txtProductName.getText());
                pstm1.setString(3, txtCompanyName.getText());
                pstm1.setInt(4, Integer.parseInt(comboProductGroup.getSelectedItem().toString().split("-")[0]));
                int addProductTable = pstm1.executeUpdate();

                String query2 = "insert into stock (stock_id, product_id, avail_stock, unit_price, sales_price, reorder_level, reorder_date)"
                        + "values (?, ?, ?, ?, ?, ?, ?)";
                pstm2 = connection.getConn().prepareCall(query2);

                pstm2.setInt(1, Integer.parseInt(txtStockID.getText()));
                pstm2.setInt(2, Integer.parseInt(txtProductID.getText()));
                pstm2.setInt(3, Integer.parseInt(txtQuantity.getText()));
                pstm2.setInt(4, Integer.parseInt(txtUnitPrice.getText()));
                pstm2.setInt(5, Integer.parseInt(txtSalesPrice.getText()));
                pstm2.setInt(6, Integer.parseInt(txtQuantity.getText()));
                pstm2.setDate(7, new java.sql.Date(txtDate.getDate().getTime()));
                int addStock = pstm2.executeUpdate();

                String query3 = "update product set stock_id=? where product_id=?";

                pstm3 = connection.getConn().prepareCall(query3);

                pstm3.setInt(1, Integer.parseInt(txtStockID.getText()));
                pstm3.setInt(2, Integer.parseInt(txtProductID.getText()));

                int updateProduct = pstm3.executeUpdate();

                JOptionPane.showMessageDialog(this, "Product saved Succesfully", "Save Confirmed", JOptionPane.INFORMATION_MESSAGE);

                pstm1.close();
                pstm2.close();
                pstm3.close();
                connection = null;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ProductEntryForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboProductGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboProductGroupActionPerformed
        // TODO add your handling code here:

        if (comboProductGroup.getSelectedIndex() == 1) {

            ProductGroup pg = new ProductGroup(new InventoryManagement(), true);
            pg.setVisible(true);

            comboProductGroup.addItem(pg.addGoup());
            comboProductGroup.setSelectedIndex(comboProductGroup.getItemCount() - 1);
           //JOptionPane.showInputDialog("Enter Group Name");

        }

    }//GEN-LAST:event_comboProductGroupActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:

        txtProductID.setText(JOptionPane.showInputDialog("Enter Product Key"));
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        productIDInitiate();
        stockIDInitiate();
        comboProductGroup.setSelectedIndex(0);
        txtProductName.setText(null);
        txtCompanyName.setText(null);
        txtUnitPrice.setText(null);
        txtSalesPrice.setText(null);
        txtQuantity.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            connection = new ConnectivitySupport();

            String query = "select * from product";

            PreparedStatement pstm = connection.getConn().prepareCall(query);

            ResultSet rs = pstm.executeQuery();
            rm.setResultSet(rs);
            productsTable.setModel(rm);
            rs.close();
            pstm.close();
            connection = null;
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AllSales.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AllSales.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    ResultsModel rm = new ResultsModel();
    private ConnectivitySupport connection;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboProductGroup;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable productsTable;
    private javax.swing.JTextField txtCompanyName;
    private com.toedter.calendar.JDateChooser txtDate;
    private javax.swing.JTextField txtProductID;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSalesPrice;
    private javax.swing.JTextField txtStockID;
    private javax.swing.JTextField txtUnitPrice;
    // End of variables declaration//GEN-END:variables
}
